ANSWER_COMMAND = {
    'REQUEST_JOIN': 'REQUESTED_JOIN',
    'UPDATE_JOIN': 'UPDATED_JOIN',
    'JOIN_NODE': 'JOINED_NODE',
    'PREPARE': 'OK',
    'PRECOMMIT': 'PRECOMMITED',
    'COMMIT': 'COMMITED',
}
